apiVersion: apps/v1
kind: Deployment
metadata:
  name: pen-app
  namespace: pen-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pen-app
  template:
    metadata:
      labels:
        app: pen-app
    spec:
      containers:
      - name: pen-app
        image: oharkins/pen-stack:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20 