apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: lapp-stack
  labels:
    app: php-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: oharkins/lapp-php:latest
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: app-volume
          mountPath: /var/www/html
      volumes:
      - name: app-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: php-app
  namespace: lapp-stack
  labels:
    app: php-app
    tier: frontend
spec:
  selector:
    app: php-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 