apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: pen-stack
type: Opaque
data:
  POSTGRES_DB: bGFwcF9kYg==  # lapp_db
  POSTGRES_USER: bGFwcF91c2Vy  # lapp_user
  POSTGRES_PASSWORD: bGFwcF9wYXNzd29yZA==  # lapp_password 