apiVersion: v1
kind: Service
metadata:
  name: pen-app-service
  namespace: pen-stack
spec:
  selector:
    app: pen-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer 